
spring.application.name=auth-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/visilog_auth_db
spring.datasource.username=postgres
spring.datasource.password=pa$$wordnaa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=visilog-auth-service-super-secret-key-change-this-later-2026
jwt.expiration=86400000