package com.visilog.api.entity;

public enum NotificationType {
    MEETING_INVITE, MEETING_DECLINED, VISIT_ADMITTED, VISIT_REJECTED,
    VISIT_CHECKED_OUT, APPOINTMENT_REQUESTED, APPOINTMENT_RESCHEDULED, CALL_LOGGED, PARTICIPANT_ABSENT
}