--
-- PostgreSQL database dump
--

\restrict 89UNGBOyw03AzpiNTXO0E41W6hBFbAgKyDG2xpqycLyjIcPDCKlKv7Czhqkmurw

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments (
    appointment_id bigint NOT NULL,
    appointment_date date NOT NULL,
    appointment_time time(6) without time zone NOT NULL,
    host_employee_email character varying(255) NOT NULL,
    purpose character varying(255) NOT NULL,
    status character varying(255),
    visitor_email character varying(255) NOT NULL,
    visitor_name character varying(255) NOT NULL,
    visitor_phone character varying(255)
);


ALTER TABLE public.appointments OWNER TO postgres;

--
-- Name: appointments_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments ALTER COLUMN appointment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    employee_id bigint NOT NULL,
    active boolean NOT NULL,
    department character varying(255),
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    office_location character varying(255),
    phone_number character varying(255),
    staff_role character varying(255)
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- Name: employees_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meetings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meetings (
    meeting_id bigint NOT NULL,
    appointment_id bigint NOT NULL,
    end_time time(6) without time zone NOT NULL,
    host_employee_email character varying(255) NOT NULL,
    meeting_date date NOT NULL,
    meeting_location character varying(255) NOT NULL,
    notes character varying(255),
    start_time time(6) without time zone NOT NULL,
    status character varying(255),
    visitor_name character varying(255) NOT NULL
);


ALTER TABLE public.meetings OWNER TO postgres;

--
-- Name: meetings_meeting_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meetings ALTER COLUMN meeting_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_meeting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: visitor_approvals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.visitor_approvals (
    approval_id bigint NOT NULL,
    appointment_id bigint NOT NULL,
    approved_by character varying(255) NOT NULL,
    decision character varying(255) NOT NULL,
    decision_date timestamp(6) without time zone,
    reason character varying(255)
);


ALTER TABLE public.visitor_approvals OWNER TO postgres;

--
-- Name: visitor_approvals_approval_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.visitor_approvals ALTER COLUMN approval_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.visitor_approvals_approval_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (appointment_id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (employee_id);


--
-- Name: meetings meetings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (meeting_id);


--
-- Name: employees ukj9xgmd0ya5jmus09o0b8pqrpb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT ukj9xgmd0ya5jmus09o0b8pqrpb UNIQUE (email);


--
-- Name: visitor_approvals visitor_approvals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visitor_approvals
    ADD CONSTRAINT visitor_approvals_pkey PRIMARY KEY (approval_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 89UNGBOyw03AzpiNTXO0E41W6hBFbAgKyDG2xpqycLyjIcPDCKlKv7Czhqkmurw

