spring.application.name=employee-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/visilog_employee_db
spring.datasource.username=postgres
spring.datasource.password=pa$$wordnaa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=visilog-auth-service-super-secret-key-change-this-later-2026